### ISSUE TITLE
Support an "everything" config attribute to merge all ressources into a single feed

### ISSUE THREAD

**Issue by whysthatso** [bridgetownrb/bridgetown-feed#10]
as mentioned by @joemasilotti in #7 it would be very neat to have a config option that generates
- a single feed.xml endpoint
- including all posts
- including all custom collections 

```
feed:
  include_all: true (default to false)
```

it should probably live along the current option to have a feed/<collection>.xml endpoint

**Comment by whysthatso** [comment]
an alternative more elaborate version could also give the option of a multifeed. In this example the site has 2 custom collections coll_1 and coll_2. the name of the feed could be default `multifeed.xml` or have a custom name. so i could overwrite `feed.xml` to become my multifeed. or have `feed.xml` behave like it currently does. 

```
feed:
  include_all: true (default to false)
  multifeed:
    collections:
      - posts
      - coll_2
     path: multifeed.xml (default)
```

one could suggest to even have multiple feeds, but i haven't really thought it all the way through, so comments are welcome.

These are possibly related issues:
https://github.com/bridgetownrb/bridgetown/issues/730
https://github.com/bridgetownrb/bridgetown/issues/384
